spring.application.name=face-recognition-service
server.port=8080

spring.datasource.url=jdbc:mysql://localhost:3306/face_recog
spring.datasource.username=root
spring.datasource.password=userpass
spring.datasource.driver-class-name=com.mysql.jdbc.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true